### ISSUE TITLE
editing without login not possible: Expected behaviour?

### ISSUE THREAD

**Issue by draptik** [gilbitron/Raneto#96] opened 2016-02-19 18:56 UTC
The current state does not allow editing pages if the user is not logged in.

`themes/default/templates/page.html`:
``` 
      {{#loggedIn}}
        {{#config.allow_editing}}
```

`app/routes/home.route.js`:
``` 
loggedIn      : (config.authentication ? req.session.loggedIn : false)
```
I was expecting to be able to edit files by these settings in `example/config_default.js`:

```
allow_editing : true,
authentication : false,
```
Is this the intended behaviour?

**Comment by ryanlelek** [comment] 2016-02-19 19:31
I agree, this is confusing.
Your expected behavior is correct, but not the current implementation after incorporating pull requests and the overall "end result" of people deploying this as a public documentation website instead of locally where default is to require login for any editing whatsoever.

How it all stacked up:
- Authentication flag came first to require login to view the documentation
- The Allow Editing flag was then added to allow logged-in users to edit

New scenarios:
- Yours, where you want editing allowed for anyone (on a trusted/controlled network)
- Require login to view documentation, not viewable or editable as guest
- Require login to edit documentation, publicly viewable as guest

**Comment by draptik** [comment] 2016-02-19 23:29
Oh. I see, thanks for your answer!

A first step might be to shift the logic from the frontend to the backend?

Maybe replace:
```
{{#loggedIn}}
        {{#config.allow_editing}}
```
with:
```
{{#canEdit}}
```

I would like to have a flag in the config file saying loud and clear 'allow-all'.

This does not match with a hierarchy of rules, I know.

What about a config flag name like
```
barebone-authentication = true
```
Ok, I am not convinced myself...

Any ideas?

**Comment by ryanlelek** [comment] 2016-02-20 19:36
Good solution, and thanks for requesting since I wasn't sure how desirable it would be.

I can dedicate time tomorrow to resolving this if you like.
Unless you would you are already digging in and planning to do a PR?

**Comment by draptik** [comment] 2016-02-21 08:37
I haven't had time to dig into this (I'll probably have a stab at issue #97 instead).

**Closed** 2016-03-03 20:46 UTC
Labels: bug
