### ISSUE TITLE
not all files displayed

### ISSUE THREAD

**Issue by laoshaw** [gilbitron/Raneto#141] opened 2016-09-07 19:48 UTC
not all files displayed correctly from content/\* when login, could not figure out the reason, it appears to be random files can not be shown at the home page.

**Comment by mohammadrafigh** [comment] 2016-09-07 20:07
can you please provide more information about it? for example maybe an screenshot of what you see and providing your file structure may help.

**Comment by laoshaw** [comment] 2016-09-07 20:49
I tried the master branch, enabled both editor and authorization, add a few markdown files under 5 different folders, out of 15 markdown files 3 are missing from the homepage and the left-sidebar, however they do exist in the filesystem.

**Comment by laoshaw** [comment] 2016-09-07 20:51
I also tried 0.9.0, when I added a few files under content/folder1/folder2, only folder2 is shown but the files under it are not shown. I'm also disappointed finding out Raneto can not display subfolders correctly which made me looking for alternatives.

show all my files, and show the correct file hierarchy on the left side, will make Raneto a great project.

**Comment by mohammadrafigh** [comment] 2016-09-07 21:06
can you please try the latest version from master branch too?

**Comment by mohammadrafigh** [comment] 2016-09-07 21:18
I couldn't be able to regenerate this issue. maybe others can.

**Comment by Sparticuz** [comment] 2016-09-08 13:21
I would verify file permissions. Make sure your webserver can access the files. As for subcategories, check out #53, it's going to happen

**Comment by stickgrinder** [comment] 2016-09-23 15:23
Sorry guys, I identified a case where this happens sistematically:

if a file contains a set of three or more dashes: `---` or  `-----` in any position, raneto crashes trying to rendering it. If you are looking at that file the service needs a full restart. If you are looking at the index the file simply isn't there.

If you change dashes with asterisks `---` -> `***` to mark a hr tag, all works. Please, try to replicate in this way and check if you are facing this kind of problem. To me the solution is simply to remove all subsequent dashes above three.

**Comment by Sparticuz** [comment] 2016-09-23 17:26
Hmm, this might be related to #157

**Comment by stickgrinder** [comment] 2016-09-23 18:16
I immediately thought about a clash between yml meta header and markdown syntax... Not sure but definitively the main suspect.

**Comment by ryanlelek** [comment] 2016-10-26 23:28
As @Sparticuz mentioned, this might be resolved by #157 
However, marking this as a bug in the meantime to not jump the gun

**Comment by shimizust** [comment] 2017-01-06 15:21
#157 does not resolve the issue. A better workaround that allows markdown files to keep dashes, which might be used for tables or inside a code block, is to just add an empty comment block to the top of the file:
```
/*
*/

# Rest of markdown file
```

I think the problem is that it's assuming there's a metadata header (using --- or /*) and trying to parse the metadata. It should be modified to account for the situation when no header is present.

**Closed** 2017-01-16 01:27 UTC
Labels: bug, help wanted, up-for-grabs
