### ISSUE TITLE
File links point to local file...

### ISSUE THREAD

**Issue by Mucaccino** [gilbitron/Raneto#126] opened 2016-06-13 20:10 UTC
Hi,

I have successful to install and configure them, but all of markdown links are pointing to the local of file, in place of the link to inner content.

The link looks like:

`http://localhost:3000/C:/HOME/Lab/Raneto/example/content/install/requirements`

Instead of:

`http://localhost:3000/install/requirements`

Has anyone encountered this, or know why it happens? How to fix? Please, help.

Thanks,

**Comment by nirmalkumarv** [comment] 2016-06-16 08:04
Same issue for me as well. I am using  Windows

**Comment by Mucaccino** [comment] 2016-06-16 20:17
Ok, I'm not alone in this.

I'm also using Windows:

- Windows 10 x64
- Node.js v5.1.0

Hugs,

**Comment by ryanlelek** [comment] 2016-06-16 23:22
Excellent. I'll install Windows in a VM this weekend to diagnose further.

In the meantime:
- Is it possible to update to Node v6.x?
- Going from memory, this is likely tied to the use of the "path.normalize(__dirname + XXXXX)" area in the config file. You might consider removing __dirname and poking around in there as a quick fix.

**Comment by ryanlelek** [comment] 2016-06-18 17:39
Confirmed, patching

**Comment by ryanlelek** [comment] 2016-06-18 18:14
Ok, so here's what's happening:
In the raneto-core module, we replace the "content directory" path defined in config.js with nothing, thus turning an absolute path into a relative path, from the project root.

This works fine on both platforms since it's just a string. However, for some reason in Windows 10, there's an additional "\" appended to the end. This switch from backslashes (\) in filepaths to more Unix-y forward slashes (/) might be new in Windows 10, to help with Unix-like compatibility. Perhaps Node.js still thinks we should have a backslash on the end (my guess) or maybe it's something in our Raneto project.

Either way, the fix is simple enough and I'll update raneto-core accordingly and republish Raneto with it soon (commenting here when I do).

Image of "before":
![Win 10 File Paths](http://cloud.ryanlelek.com/1F2037373Y10/raneto_win10_filepaths.png)

After patching with `content_dir = content_dir.replace('/\\', '/')`:
![Win 10 File Paths Patched](http://cloud.ryanlelek.com/3V0334333K3j/raneto_win10_filepaths_patched.png)

**Comment by ryanlelek** [comment] 2016-06-18 18:39
Fixed in v0.10.1
Please upgrade and try again to confirm.

Thanks for reporting and choosing Raneto!

**Comment by Mucaccino** [comment] 2016-06-18 21:36
Than you, @ryanlelek!
Always a few additional steps are required for a multi-platform project.
This project is simple, light, but awesome.
I'wanna update and try the fix.
Hugs,

**Comment by Mucaccino** [comment] 2016-06-18 22:03
The fix works!

![image](https://cloud.githubusercontent.com/assets/399292/16173934/c0bec562-3586-11e6-8aa5-4528eca78a67.png)

Again, thanks.

**Comment by nirmalkumarv** [comment] 2016-06-20 07:42
Yes the latest fix works good.

**Comment by ryanlelek** [comment] 2017-01-16 01:56
Glad we got it figured out. Closing

**Closed by ryanlelek** 2017-01-16 01:56 UTC
Labels: bug, pending
