### ISSUE TITLE
Does not install correctly with npm 3+

### ISSUE THREAD

**Issue by sinedied** [gilbitron/Raneto#119] opened 2016-05-19 14:55 UTC
I just tried using Raneto in my project, but the `copy_libs` gulp task fails when installed using npm 3+: newer npm version tries to flatten the node_modules dependendy tree, and so bootstrap and other libs gets installed in my root node_modules folder, not in the raneto folder causing the files not to be copied as expected.

For the information, I have node v5.0.0 and npm 3.8.2 installed on my system.

**Comment by ryanlelek** [comment] 2016-06-05 20:22
Hi there @sinedied,

I tried it just now with the following OS and versions and it is working.
Perhaps NPM had an internal bug that was resolved in the many releases.
Could you update your Node/NPM version set and try again?
If you're still having issues, please send your OS too so I can test on your specific platform
```
OS: Mac OS X 10.9.5
Node: v5.11.1
NPM: v3.8.6
```

**Comment by ryanlelek** [comment] 2016-09-10 23:55
Closing due to inactivity.
Please reopen if you're still experiencing issues

**Closed by ryanlelek** 2016-09-10 23:55 UTC
Labels: bug, pending

**Comment by sinedied** [comment] 2016-09-19 13:00
Just tried again, same issue but maybe I'm doing something wrong, here is how I setup the project:

* `npm install raneto` on my project
* add `raneto.server.js` on the project root, based on example
* add `config.js` on the project root, based on example with theme_dir/public_dir changed to target `__dirname + "/node_modules/raneto/themes/"
* start raneto with `node raneto.server.js`

Raneto starts, but every external depencies loading fails with a 404:
```
GET / 200 197.828 ms - 4450
GET /styles/raneto.css 200 10.011 ms - 2640
GET /lib/bootstrap/dist/css/bootstrap.min.css 404 24.208 ms - 1988
GET /lib/highlightjs/styles/solarized_light.css 404 24.138 ms - 1988
GET /styles/ghostdown.css 200 12.421 ms - 12082
GET /lib/jquery/dist/jquery.min.js 404 6.838 ms - 1988
GET /lib/bootstrap/dist/js/bootstrap.min.js 404 7.675 ms - 1988
GET /lib/highlightjs/highlight.pack.min.js 404 4.063 ms - 1988
GET /lib/fitvids/fitvids.min.js 404 18.662 ms - 1988
GET /lib/masonry-layout/dist/masonry.pkgd.min.js 404 17.621 ms - 1988
GET /scripts/raneto.js 200 9.064 ms - 4681
GET /scripts/ghostdown.js 200 10.261 ms - 254264
GET /api-proxy 200 274.215 ms - 7173
GET /lib/bootstrap/dist/css/bootstrap.min.css 404 6.956 ms - 1988
GET /lib/highlightjs/styles/solarized_light.css 404 6.127 ms - 1988
GET /styles/raneto.css 304 9.538 ms - -
GET /styles/ghostdown.css 304 0.914 ms - -
GET /lib/jquery/dist/jquery.min.js 404 4.118 ms - 1988
GET /lib/bootstrap/dist/js/bootstrap.min.js 404 2.356 ms - 1988
GET /scripts/ghostdown.js 304 1.639 ms - -
GET /scripts/raneto.js 304 0.362 ms - -
GET /lib/highlightjs/highlight.pack.min.js 404 2.043 ms - 1988
GET /lib/fitvids/fitvids.min.js 404 5.608 ms - 1988
GET /lib/masonry-layout/dist/masonry.pkgd.min.js 404 3.964 ms - 1988
GET /cordova 200 268.188 ms - 17601
GET /lib/bootstrap/dist/css/bootstrap.min.css 404 2.685 ms - 1988
GET /lib/highlightjs/styles/solarized_light.css 404 1.892 ms - 1988
GET /styles/raneto.css 304 1.085 ms - -
GET /styles/ghostdown.css 304 4.321 ms - -
GET /lib/jquery/dist/jquery.min.js 404 5.516 ms - 1988
GET /lib/bootstrap/dist/js/bootstrap.min.js 404 5.017 ms - 1988
GET /scripts/ghostdown.js 304 0.486 ms - -
GET /scripts/raneto.js 304 0.710 ms - -
GET /lib/highlightjs/highlight.pack.min.js 404 2.242 ms - 1988
GET /lib/fitvids/fitvids.min.js 404 2.854 ms - 1988
GET /lib/masonry-layout/dist/masonry.pkgd.min.js 404 1.641 ms - 1988
```

**Comment by ChimeraFire** [comment] 2020-01-10 18:24
This is happening for me too. I think the issue is that `node_modules/raneto/gulpfile.js` is trying to copy from (for example) `node_modules/jquery/**/*` (that path is relative to the gulpfile, so..  `node_modules/raneto/node_modules/jquery/**/*` from my project root) which doesn't exist.

If you just download the release zip and use that, it works ok because raneto itself is not in node_modules, and the relative path for the gulpfile makes sense. It is a path relative to raneto as the main project.

To fix this, you could look for the files at one path (`node_modules/jquery/**/*` for zip installation), and if the path is invalid, try the other (I'm guessing `../jquery/**/*` for npm installation). 
Or include the libs in the nested node_modules directory of the npm installation (though duplicating these modules is not ideal)... 
Or come up with a better solution since you know more about how you want your project structured than I do!
